
# NumPy Arrays and Pandas Series Exercises

<a href = #numpy> 1. NumPy Array</a>

- <a href = #array_index> 1.2. NumPy Indexing</a>
    - <a href = #array_index1> 1.2.1 Array Slicing </a>
    - <a href = #array_index2> 1.2.2  Integer Array Indexing</a> 

<a href = #pandas> 2. Pandas Series</a>
- <a href = #pandas_alignment>Alignment of Series objects</a>



In [1]:
import numpy as np
import pandas as pd

<a id = 'numpy'></a>
## NumPy Arrays


In [ ]:
#Exercise 1: Are a and b the same?
a = np.arange(1,10,2)
b = np.linspace(1,10,2)
print(a)
print(b)

In [2]:
#Answer: No
a = np.arange(1,10,2) # creates elements in a range [1:10), incrementing values by 2\\
b = np.linspace(1,10,2) # creates a specified number of elements (2) in a range (1 to 10 including), equally spaced
print(a)
print(b)

[1 3 5 7 9]
[  1.  10.]


<a id = 'array_index'></a>
### 1.2 Array indexing

<a id = 'array_index1'></a>
#### 1.2.1 Array slicing

In [ ]:
# Exercise 2:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2,1:3] # get first two rows and 2nd and 3rd columns
b[0,0]=99
# What is the output of the following line?
print(a[0,1])

In [3]:
# Answer:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2,1:3] # get first two rows and 2nd and 3rd columns
b[0,0]=99
# What is the output of the following line?
print(a[0,1]) # 99 , because we changed the value in a view b, which automatically changes the corresponding value in an original array

99


In [ ]:
#Exercise 3: what are the ranks of the following views?
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_1 = a[1:2,:] 
row_2 = a[1,:] 
print(row_1)
print(row_2)

In [6]:
#Answer: rank 2 and rank 1 arrays respectively
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_1 = a[1:2,:] # returns rank 2 view of the second row of a
row_2 = a[1,:] # returns a rank 1 view of the second row of a
print(row_1)
print(row_2)

[[5 6 7 8]]
[5 6 7 8]


<a id ='array_index2'></a>
#### 1.2.2 Integer array indexing

In [ ]:
# Exercise 4: what is the output of the following code?
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
idx = np.array([0,1,2,2])

a[np.arange(4),idx]+=np.array([1,1,1,1])

a.copy()[np.arange(4),idx]+=10

print(a)

In [12]:
#Answer:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
idx = np.array([0,1,2,2]) # Create an array of indices

a[np.arange(4),idx]+=np.array([99,99,99,99]) # Mutate one element from each row of a using the indices in idx. 
                        #Since slicing produces the view, we will change the original values of a

a.copy()[np.arange(4),idx]+=10 #Mutate one element from each row of a COPY of a using the indices in idx

print(a)

[[100   2   3]
 [  4 104   6]
 [  7   8 108]
 [ 10  11 111]]


<a id = 'pandas'></a>
## Pandas Series

In [ ]:
#Exercise 5: what is the output of the following code?
import pandas as pd
import string

mySeries = pd.Series(np.arange(5),index = list(string.ascii_lowercase[0:len(np.arange(5))]), dtype = 'float')
print(mySeries[3:])
print(mySeries[:-2])
myS = mySeries[['a','c','e','f']] 
print(myS)

In [177]:
#Answer:
mySeries = pd.Series(np.arange(5),index = list(string.ascii_lowercase[0:len(np.arange(5))]), dtype = 'float')
print(mySeries[3:])
print(mySeries[:-2])
myS = mySeries[['a','c','e','f']] 
print(myS) # doesn't raise the error but adds an index 'f' with value NaN

d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
c    2.0
dtype: float64
a    0.0
c    2.0
e    4.0
f    NaN
dtype: float64


/Users/owner/anaconda/envs/fastai/lib/python3.6/site-packages/pandas/core/series.py:705: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


When using non-zero based integer indices we might quickly get confused.

In [ ]:
#Exercise 6_a:
mySeries3 = pd.Series(np.arange(6,11), index = np.arange(11,16))
print(mySeries3[12])
print(mySeries3[1]) 

In [13]:
#Answer:
mySeries3 = pd.Series(np.arange(6,11), index = np.arange(11,16))
print(mySeries3[12]) #print 7
print(mySeries3[1]) # KeyError is raised

7


KeyError: 1

In [ ]:
#Exercise 6_b: what is the output of the following code?
print(mySeries3.iloc[1])
print(mySeries3.loc[12])

In [15]:
#Answer:
print(mySeries3.iloc[1])# postion-based search
print(mySeries3.loc[12]) # label-based search

7
7


<a id = 'pandas_alignment'></a>
### Alignment of Series objects

In [ ]:
#Exercise 7:
#Are the values of NumPy array and Pandas Series the same (ignoring the series index): 
n = np.arange(5)
s = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
print(n[1:])
print(s[1:])
# What about the results of these operations?
print(n[1:]+n[:-1])
print(s[1:]+s[:-1])

In [114]:
#Answer
#Are the values of NumPy array and Pandas Series the same (ignoring the series index): 
n = np.arange(5)
s = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
print(n[1:])
print(s[1:]) # yes, we get the same values 1,2,3,4


# What about the results of these operations?
print(n[1:]+n[:-1])
print(s[1:]+s[:-1]) # Pandas series adds the values with the same index! If the index is missing, NaN is produces

[1 2 3 4]
b    1
c    2
d    3
e    4
dtype: int64
[1 3 5 7]
a    NaN
b    2.0
c    4.0
d    6.0
e    NaN
dtype: float64
